# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "54ea3e53b2999aa0cacb9472be02e692"
name = "customer-accounts"
handle = "customer-accounts-50"
application_url = "https://page-valuation-trek-korea.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://page-valuation-trek-korea.trycloudflare.com/auth/callback",
  "https://page-valuation-trek-korea.trycloudflare.com/auth/shopify/callback",
  "https://page-valuation-trek-korea.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
